CREATE OR REPLACE PROCEDURE GENERATE_TOTAL_HOURS_REPORT AS
    CURSOR C_EMPLOYEE_HOURS IS
        SELECT 
            E.EMP_ID,
            E.EMP_NAME,
            E.DEPARTMENT,
            SUM(WH.HOURS_WORKED) AS TOTAL_HOURS,
            COUNT(WH.ID) AS LOG_ENTRIES
        FROM 
            EMPLOYEES E
        JOIN 
            EMPLOYEES_WORKHOUR_LOGS WH ON E.EMP_ID = WH.EMP_ID
        GROUP BY 
            E.EMP_ID, E.EMP_NAME, E.DEPARTMENT
        ORDER BY 
            E.DEPARTMENT, E.EMP_NAME;
    
BEGIN
    DBMS_OUTPUT.PUT_LINE('TOTAL HOURS WORKED BY EMPLOYEE');
    DBMS_OUTPUT.PUT_LINE('-----------------------------');
    DBMS_OUTPUT.PUT_LINE('EMP_ID,EMP_NAME,DEPARTMENT,TOTAL_HOURS,LOG_ENTRIES');
    
    FOR EMP_REC IN C_EMPLOYEE_HOURS LOOP
        DBMS_OUTPUT.PUT_LINE(
            EMP_REC.EMP_ID || ',' ||
            EMP_REC.EMP_NAME || ',' ||
            EMP_REC.DEPARTMENT || ',' ||
            EMP_REC.TOTAL_HOURS || ',' ||
            EMP_REC.LOG_ENTRIES
        );
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE('-----------------------------');
    DBMS_OUTPUT.PUT_LINE('REPORT COMPLETED');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
        RAISE;
END GENERATE_TOTAL_HOURS_REPORT;
/
