BEGIN
    DBMS_SCHEDULER.CREATE_JOB (
        JOB_NAME        => 'EMPLOYEE_WEEKLY_HOURS_REPORT_JOB',  
        JOB_TYPE        => 'PLSQL_BLOCK',              
        JOB_ACTION      => 'BEGIN GENERATE_WEEKLY_HOURS_REPORT; END;',  
        START_DATE      => SYSTIMESTAMP,               
        REPEAT_INTERVAL => 'FREQ=WEEKLY; BYDAY=MON; BYHOUR=8', 
        ENABLED         => TRUE,                       
        COMMENTS        => 'GENERATES WEEKLY EMPLOYEE WORK HOURS REPORT'  
    );
    
    -- CONFIRMATION MESSAGE
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE WEEKLY HOUR REPORT CREATED SUCCESSFULLY');
    
EXCEPTION
    -- ERROR HANDLING SECTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR CREATING JOB: ' || SQLERRM);
END;
/