CREATE TABLE EMPLOYEES (
    EMP_ID NUMBER PRIMARY KEY,
    EMP_NAME VARCHAR2(50),
    DEPARTMENT VARCHAR2(50),
    EMAIL VARCHAR2(100)
);

CREATE TABLE EMPLOYEES_WORKHOUR_LOGS (
    ID NUMBER PRIMARY KEY,
    EMP_ID NUMBER,
    HOURS_WORKED NUMBER(5,2),
    CREATED_DATE DATE,
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES (EMP_ID)
);

CREATE INDEX IDX_WORKHOUR_LOGS_EMP_ID ON EMPLOYEES_WORKHOUR_LOGS (EMP_ID);
CREATE INDEX IDX_WORKHOUR_LOGS_CREATED_DATE ON EMPLOYEES_WORKHOUR_LOGS (CREATED_DATE);
